name: Forge Framework CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: |
          package-lock.json
          ai-dual-mode/package-lock.json

    - name: Install dependencies in ai-dual-mode
      working-directory: ./ai-dual-mode
run: |
  if [ -f package-lock.json ]; then
    npm ci
  else
    npm install
  fi

    - name: Lint ai-dual-mode
      working-directory: ./ai-dual-mode
      run: npm run lint

    - name: Install dependencies in packages/test-framework
      working-directory: ./packages/test-framework
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        else
          npm install
        fi

    - name: Test ai-dual-mode
      working-directory: ./ai-dual-mode
      run: npm run test:coverage

    - name: Test test-framework
      working-directory: ./packages/test-framework
      run: npm run test:coverage

    - name: Build ai-dual-mode (if build script exists)
      working-directory: ./ai-dual-mode
      run: npm run build || echo "No build script found, skipping"

    - name: Build test-framework (if build script exists)
      working-directory: ./packages/test-framework
      run: npm run build || echo "No build script found, skipping"
