name: PR Linter

on:
  pull_request:
    paths:
      - '**/*.js'
      - '**/*.md'
      - '.github/workflows/pr-linter.yml'
      - 'tools/pr-linter.js'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run PR Linter
        run: node tools/pr-linter.js
